[package]
name = "ucph_slides"
version = "0.1.0"
entrypoint = "lib.typ"
compiler = "0.13.0"
authors = ["Jørgen Baun Høst <https://github.com/jorgenhost/Typst-templates-for-UCPH/tree/main/ucph_Slides>"]
license = "GPL-3.0"
description = "Minimalistic Typst slides for the University of Copenhagen."
repository = "https://github.com/jorgenhost/Typst-templates-for-UCPH/tree/main/ucph_Slides"
keywords = ["slides", "presentation", "Copenhagen"]
categories = ["presentation", "layout", "components"]
exclude = ["img", ".github"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "xxx.png"
